/*$file${../application::gui_mngr.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: snmtt.qm
* File:  ${../application::gui_mngr.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../application::gui_mngr.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*==========================================================================*/
#include "qpc.h"
#include "bsp.h"
#include "application.h"

/*==========================================================================*/
/* ===GuiMngr Active Object (AO) class. */
/*$declare${AOs::GuiMngr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::GuiMngr} ..........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* public: */
    QTimeEvt timeEvt;
} GuiMngr;

/* protected: */
static QState GuiMngr_initial(GuiMngr * const me, void const * const par);
static QState GuiMngr_active(GuiMngr * const me, QEvt const * const e);
static QState GuiMngr_opened(GuiMngr * const me, QEvt const * const e);
static QState GuiMngr_closed(GuiMngr * const me, QEvt const * const e);
static QState GuiMngr_opening(GuiMngr * const me, QEvt const * const e);
static QState GuiMngr_closing(GuiMngr * const me, QEvt const * const e);
/*$enddecl${AOs::GuiMngr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*==========================================================================*/
/* ===AO instance. */
static GuiMngr GuiMngr_inst;
QActive * const AO_GuiMngr = &GuiMngr_inst.super;

/*==========================================================================*/
void GuiMngr_ctor(void) {
    /* 'me' points to the Blinky instance. */
    GuiMngr * const me = &GuiMngr_inst;

    /* call the superclass' constructor. */
    QActive_ctor(&me->super, Q_STATE_CAST(&GuiMngr_initial));

    /* call the members' constructors. */
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}

/*..........................................................................*/
/* ...State machine. */
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::GuiMngr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::GuiMngr} ..........................................................*/

/*${AOs::GuiMngr::SM} ......................................................*/
static QState GuiMngr_initial(GuiMngr * const me, void const * const par) {
    /*${AOs::GuiMngr::SM::initial} */
    Q_UNUSED_PAR(par); // initialization parameter unused in this case
    return Q_TRAN(&GuiMngr_active);
}

/*${AOs::GuiMngr::SM::active} ..............................................*/
static QState GuiMngr_active(GuiMngr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::GuiMngr::SM::active::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&GuiMngr_closed);
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_CLICK_REFRESH_BUTTON} */
        case GUI_CLICK_REFRESH_BUTTON_SIG: {
            QEvt *evt = Q_NEW(QEvt, SP_MNGR_REFRESH_SERIAL_PORT_SIG);
            QACTIVE_POST(AO_SpMngr, (QEvt *)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_UPDATE_COM} */
        case GUI_UPDATE_COM_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_UPDATE_COM_SELECTION_SIG);
            evt->pld.txt = ((GuiMngrEvt *)e)->txt;
            QACTIVE_POST(AO_SpMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_UPDATE_BAUDRATE} */
        case GUI_UPDATE_BAUDRATE_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_UPDATE_BAUDRATE_SIG);
            evt->pld.txt = ((GuiMngrEvt *)e)->txt;
            QACTIVE_POST(AO_SpMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_UPDATE_DATABITS} */
        case GUI_UPDATE_DATABITS_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_UPDATE_DATABITS_SIG);
            evt->pld.txt = ((GuiMngrEvt *)e)->txt;
            QACTIVE_POST(AO_SpMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_UPDATE_STOPBITS} */
        case GUI_UPDATE_STOPBITS_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_UPDATE_STOPBITS_SIG);
            evt->pld.txt = ((GuiMngrEvt *)e)->txt;
            QACTIVE_POST(AO_SpMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_UPDATE_PARITY} */
        case GUI_UPDATE_PARITY_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_UPDATE_PARITY_SIG);
            evt->pld.txt = ((GuiMngrEvt *)e)->txt;
            QACTIVE_POST(AO_SpMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_UPDATE_FLOWCONTROL} */
        case GUI_UPDATE_FLOWCONTROL_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_UPDATE_FLOWCONTROL_SIG);
            evt->pld.txt = ((GuiMngrEvt *)e)->txt;
            QACTIVE_POST(AO_SpMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_GET_UPDATED_COM_INFO} */
        case GUI_GET_UPDATED_COM_INFO_SIG: {
            SDL_Event event;
            SDL_zero(event);
            event.type = DISP_UPDATE_COM_DROPDOWN_BOX_INFO_SIG;
            event.user.data1 = (void *)((((GuiMngrEvt *)e)->txt));
            SDL_PushEvent(&event);  /* thread-safe push */
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_OPEN_INVALID_COM} */
        case GUI_OPEN_INVALID_COM_SIG: {
            status_ = Q_TRAN(&GuiMngr_active);
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_MNGR_PORT_ERR_SHUT_DOWN} */
        case GUI_MNGR_PORT_ERR_SHUT_DOWN_SIG: {
            status_ = Q_TRAN(&GuiMngr_active);
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_MNGR_UPDATE_SELECTED_JSON_FI~} */
        case GUI_MNGR_UPDATE_SELECTED_JSON_FILE_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_UPDATE_SELECTED_JSON_FILE_SIG);
            evt->pld.txt = ((GuiMngrEvt *)e)->txt;
            QACTIVE_POST(AO_SpMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_MNGR_LOAD_SELECTED_JSON_FILE} */
        case GUI_MNGR_LOAD_SELECTED_JSON_FILE_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_LOAD_SELECTED_JSON_FILE_SIG);
            QACTIVE_POST(AO_SpMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_MNGR_RECV_MSG} */
        case GUI_MNGR_RECV_MSG_SIG: {
            /* Send the *txt to Display */
            SDL_Event event;
            SDL_zero(event);
            event.type = DISP_UPDATE_RECV_BOX_MSG_SIG;
            event.user.data1 = (void *)((((GuiMngrEvt *)e)->txt));
            SDL_PushEvent(&event);  /* thread-safe push */
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::GUI_MNGR_UPDATE_LOADED_JSON_FILE} */
        case GUI_MNGR_UPDATE_LOADED_JSON_FILE_SIG: {
            SDL_Event event;
            SDL_zero(event);
            event.type = DISP_UPDATE_LOADED_JSON_FILE_SIG;
            event.user.data1 = (void *)((((GuiMngrEvt *)e)->txt));
            SDL_PushEvent(&event);  /* thread-safe push */
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::GuiMngr::SM::active::opened} ......................................*/
static QState GuiMngr_opened(GuiMngr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::GuiMngr::SM::active::opened} */
        case Q_ENTRY_SIG: {
            SDL_Event event;
            SDL_zero(event);
            event.type = DISP_UPDATE_OPEN_STATE_SIG;
            SDL_PushEvent(&event);  /* thread-safe push */
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::opened::GUI_CLICK_OPEN_CLOSE_BUTTON} */
        case GUI_CLICK_OPEN_CLOSE_BUTTON_SIG: {
            /* Close port */
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_CLOSE_SERIAL_PORT_SIG);
            QACTIVE_POST(AO_SpMngr, (QEvt *)evt, (void *)0);
            status_ = Q_TRAN(&GuiMngr_closing);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMngr_active);
            break;
        }
    }
    return status_;
}

/*${AOs::GuiMngr::SM::active::closed} ......................................*/
static QState GuiMngr_closed(GuiMngr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::GuiMngr::SM::active::closed} */
        case Q_ENTRY_SIG: {
            SDL_Event event;
            SDL_zero(event);
            event.type = DISP_UPDATE_CLOSE_STATE_SIG;
            SDL_PushEvent(&event);  /* thread-safe push */
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::closed::GUI_CLICK_OPEN_CLOSE_BUTTON} */
        case GUI_CLICK_OPEN_CLOSE_BUTTON_SIG: {
            SpMngrEvt *evt = Q_NEW(SpMngrEvt, SP_MNGR_OPEN_SERIAL_PORT_SIG);
            QACTIVE_POST(AO_SpMngr, (QEvt *)evt, (void *)0);
            status_ = Q_TRAN(&GuiMngr_opening);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMngr_active);
            break;
        }
    }
    return status_;
}

/*${AOs::GuiMngr::SM::active::opening} .....................................*/
static QState GuiMngr_opening(GuiMngr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::GuiMngr::SM::active::opening} */
        case Q_ENTRY_SIG: {
            SDL_Event event;
            SDL_zero(event);
            event.type = DISP_UPDATE_OPENING_STATE_SIG;
            SDL_PushEvent(&event);  /* thread-safe push */
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::opening::GUI_OPEN_COM_SUCCESS} */
        case GUI_OPEN_COM_SUCCESS_SIG: {
            status_ = Q_TRAN(&GuiMngr_opened);
            break;
        }
        /*${AOs::GuiMngr::SM::active::opening::GUI_OPEN_COM_FAIL} */
        case GUI_OPEN_COM_FAIL_SIG: {
            status_ = Q_TRAN(&GuiMngr_active);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMngr_active);
            break;
        }
    }
    return status_;
}

/*${AOs::GuiMngr::SM::active::closing} .....................................*/
static QState GuiMngr_closing(GuiMngr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::GuiMngr::SM::active::closing} */
        case Q_ENTRY_SIG: {
            SDL_Event event;
            SDL_zero(event);
            event.type = DISP_UPDATE_CLOSING_STATE_SIG;
            SDL_PushEvent(&event);  /* thread-safe push */
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::GuiMngr::SM::active::closing::GUI_MNGR_CLOSE_COM_SUCCESS} */
        case GUI_MNGR_CLOSE_COM_SUCCESS_SIG: {
            status_ = Q_TRAN(&GuiMngr_active);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMngr_active);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::GuiMngr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
