/*$file${../application::sp_mngr.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: snmtt.qm
* File:  ${../application::sp_mngr.h}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../application::sp_mngr.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*==========================================================================*/
#ifndef SP_MNGR_H_
#define SP_MNGR_H_

/*==========================================================================*/
extern QActive * const AO_SpMngr; /* Global opaque pointer. */

/*==========================================================================*/
void SpMngr_ctor(void);

/*==========================================================================*/
/* ===lspThread events. */
#include "spthread_evt.h"

/*==========================================================================*/
/* ===Json file parser. */
#include "snmtt_json_parser.h"

/*==========================================================================*/
/* ===HLDC bytes parser. */
#include "snmtt_hldc_parser.h"

#endif  /* SP_MNGR_H_ */
