/*$file${../application::sp_mngr.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: snmtt.qm
* File:  ${../application::sp_mngr.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../application::sp_mngr.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*==========================================================================*/
#include "qpc.h"
#include "bsp.h"
#include "application.h"

/*==========================================================================*/
Q_DEFINE_THIS_MODULE("sp_mngr")

/*==========================================================================*/
/* ===SpMngr Active Object (AO) class. */
/*$declare${AOs::SpMngr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SpMngr} ...........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* public: */
    QTimeEvt timeEvt;
    char com[64];
    int baudrate;
    int dataBits;
    SerialStopBits_t stopBits;
    SerialParity_t parity;
    SerialFlow_t flowControl;
    char * currJsonFile;
} SpMngr;

/* protected: */
static QState SpMngr_initial(SpMngr * const me, void const * const par);
static QState SpMngr_active(SpMngr * const me, QEvt const * const e);
static QState SpMngr_opening(SpMngr * const me, QEvt const * const e);
static QState SpMngr_opened(SpMngr * const me, QEvt const * const e);
/*$enddecl${AOs::SpMngr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*==========================================================================*/
/* ===AO instance. */
SpMngr SpMngr_inst;
QActive * const AO_SpMngr = &SpMngr_inst.super;

/*==========================================================================*/
void SpMngr_ctor(void) {
    /* 'me' points to the Blinky instance. */
    SpMngr * const me = &SpMngr_inst;

    /* call the superclass' constructor. */
    QActive_ctor(&me->super, Q_STATE_CAST(&SpMngr_initial));

    /* call the members' constructors. */
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);

    /* default constructor... */
    me->com[0] = 'N'; me->com[1] = 'U'; me->com[2] = 'L'; me->com[3] = 'L';
    me->com[4] = '\0';

    me->baudrate    = 115200;
    me->dataBits    = 8;
    me->stopBits    = SP_STOPBITS_1_OP;
    me->parity      = SP_PARITY_NONE_OP;
    me->flowControl = SP_FLOW_NONE_OP;

    /* Default !NULL, for GC operation. */
    me->currJsonFile = strdup("Empty");

    HLDCPaser_ctor();
}

/*==========================================================================*/
/* ...String -> Int */
int str_to_baud(const char *str) {
    if (!str) return 115200; /* Default. */
    return atoi(str);
}
/*..........................................................................*/
/* ...String -> Int. */
int str_to_databits(const char *str) {
    if (!str) return 8;
    return atoi(str); // "8" -> 8, "5" -> 5
}
/*..........................................................................*/
/* ...String -> Enum. */
SerialStopBits_t str_to_stopbits(const char *str) {
    if (!str) return SP_STOPBITS_1_OP;
    if (strcmp(str, "1.5") == 0) {
        return SP_STOPBITS_1_5_OP;
    } else if (strcmp(str, "2") == 0) {
        return SP_STOPBITS_2_OP;
    } else {
        return SP_STOPBITS_1_OP;
    }
}
/*..........................................................................*/
/* ...String -> Enum. */
SerialParity_t str_to_parity(const char *str) {
    if (!str) return SP_PARITY_NONE_OP;
    if (strcmp(str, "Odd") == 0)        return SP_PARITY_ODD_OP;
    else if (strcmp(str, "Even") == 0)  return SP_PARITY_EVEN_OP;
    else if (strcmp(str, "Mark") == 0)  return SP_PARITY_MARK_OP;
    else if (strcmp(str, "Space") == 0) return SP_PARITY_SPACE_OP;
    return SP_PARITY_NONE_OP;
}
/*..........................................................................*/
/* ...String -> Enum. */
SerialFlow_t str_to_flowcontrol(const char *str) {
    if (!str) return SP_FLOW_NONE_OP;
    if (strcmp(str, "Xon/Xoff") == 0)   return SP_FLOW_XON_XOFF_OP;
    else if (strcmp(str, "RTS/CTS") == 0) return SP_FLOW_RTS_CTS_OP;
    else if (strcmp(str, "DTR/DSR") == 0) return SP_FLOW_DTR_DSR_OP;
    return SP_FLOW_NONE_OP;
}
/*..........................................................................*/
bool SpMngr_comNameIsInvalid(char *comName) {
    if (
        (strcmp(comName, "NULL") == 0) ||
            (strcmp(comName, "ERROR") == 0)
    ) {
        return false;
    }
    return true;
}

/*..........................................................................*/
/* ...State machine. */
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::SpMngr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SpMngr} ...........................................................*/

/*${AOs::SpMngr::SM} .......................................................*/
static QState SpMngr_initial(SpMngr * const me, void const * const par) {
    /*${AOs::SpMngr::SM::initial} */
    Q_UNUSED_PAR(par); // initialization parameter unused in this case
    return Q_TRAN(&SpMngr_active);
}

/*${AOs::SpMngr::SM::active} ...............................................*/
static QState SpMngr_active(SpMngr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SpMngr::SM::active::SP_MNGR_REFRESH_SERIAL_PORT} */
        case SP_MNGR_REFRESH_SERIAL_PORT_SIG: {
            BSP_Post2LspThread(
                SP_TRD_UPDATE_SERIAL_PORTS_SIG,
                (char *)0,
                115200,
                8,
                SP_STOPBITS_1_OP,
                SP_PARITY_NONE_OP,
                SP_FLOW_NONE_OP);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_UPDATE_DATABITS} */
        case SP_MNGR_UPDATE_DATABITS_SIG: {
            /* update */
            me->dataBits = str_to_databits(((SpMngrEvt *)e)->pld.txt);
            free(((SpMngrEvt *)e)->pld.txt);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_GET_UPDATED_COM_INFO} */
        case SP_MNGR_GET_UPDATED_COM_INFO_SIG: {
            GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_GET_UPDATED_COM_INFO_SIG);
            evt->txt = ((SpMngrEvt *)e)->pld.portLst;
            QACTIVE_POST(AO_GuiMngr, (QEvt *)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_UPDATE_COM_SELECTION} */
        case SP_MNGR_UPDATE_COM_SELECTION_SIG: {
            /* update */
            strcpy(me->com, ((SpMngrEvt *)e)->pld.txt);
            free(((SpMngrEvt *)e)->pld.txt);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_UPDATE_BAUDRATE} */
        case SP_MNGR_UPDATE_BAUDRATE_SIG: {
            /* update */
            me->baudrate = str_to_baud(((SpMngrEvt *)e)->pld.txt);
            free(((SpMngrEvt *)e)->pld.txt);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_UPDATE_STOPBITS} */
        case SP_MNGR_UPDATE_STOPBITS_SIG: {
            /* update */
            me->stopBits = str_to_stopbits(((SpMngrEvt *)e)->pld.txt);
            free(((SpMngrEvt *)e)->pld.txt);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_UPDATE_PARITY} */
        case SP_MNGR_UPDATE_PARITY_SIG: {
            /* update */
            me->parity = str_to_parity(((SpMngrEvt *)e)->pld.txt);
            free(((SpMngrEvt *)e)->pld.txt);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_UPDATE_FLOWCONTROL} */
        case SP_MNGR_UPDATE_FLOWCONTROL_SIG: {
            /* update */
            me->flowControl = str_to_flowcontrol(((SpMngrEvt *)e)->pld.txt);
            free(((SpMngrEvt *)e)->pld.txt);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_OPEN_SERIAL_PORT} */
        case SP_MNGR_OPEN_SERIAL_PORT_SIG: {
            /*${AOs::SpMngr::SM::active::SP_MNGR_OPEN_SER~::[SpMngr_comNameIsInvalid(me->com~} */
            if (SpMngr_comNameIsInvalid(me->com)) {
                BSP_Post2LspThread(
                    SP_TRD_OPEN_PORT_SIG,
                    me->com,
                    me->baudrate,
                    me->dataBits,
                    me->stopBits,
                    me->parity,
                    me->flowControl);
                status_ = Q_TRAN(&SpMngr_opening);
            }
            /*${AOs::SpMngr::SM::active::SP_MNGR_OPEN_SER~::[else]} */
            else {
                GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_OPEN_INVALID_COM_SIG);
                QACTIVE_POST(AO_GuiMngr, (QEvt*)evt, (void *)0);
                status_ = Q_HANDLED();
            }
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_RECV_PACKET} */
        case SP_MNGR_RECV_PACKET_SIG: {
            /* In case of memory leaking. */
            free(((SpMngrEvt *)e)->pld.packBuf);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_UPDATE_SELECTED_JSON_FIL~} */
        case SP_MNGR_UPDATE_SELECTED_JSON_FILE_SIG: {
            if (me->currJsonFile) free(me->currJsonFile);
            me->currJsonFile = ((SpMngrEvt *)e)->pld.txt;
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_LOAD_SELECTED_JSON_FILE} */
        case SP_MNGR_LOAD_SELECTED_JSON_FILE_SIG: {
            /* Load the target json file to local */
            SNMTT_loadJSONConfig(me->currJsonFile);

            /* Update loaded json file to Display... */
            GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_MNGR_UPDATE_LOADED_JSON_FILE_SIG);
            evt->txt = strdup(me->currJsonFile);
            QACTIVE_POST(AO_GuiMngr, (QEvt*)evt, (void *)0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::SP_MNGR_RECV_MSG} */
        case SP_MNGR_RECV_MSG_SIG: {
            /* Unpackage [Seq.] [RecID] [pldLen] [payload...]... */
            uint8_t *currMsg = ((SpMngrEvt *)e)->pld.msgFrm;
            SNMTT_PayloadParser *recIdParser = SNMTT_RX_getRecID(currMsg[1]);
            if (recIdParser != NULL) {  /* Valid RecID. */
                uint8_t pldSize = currMsg[2];
                uint8_t pldSizeIter = pldSize;
                uint8_t *pldStart = currMsg + 3;
                uint16_t msgSize = strlen(recIdParser->format) + 1; /* '\0'. */
                msgSize += 6;  /* "[%03d]" "... ..." */
                char *nFmt = malloc(msgSize);
                Q_ENSURE(nFmt != NULL);
                /* Format update. */
                snprintf(nFmt, msgSize,
                        "[%%03d]%s", recIdParser->format);
                msgSize = strlen(nFmt);
                char *fmtArgv[SNMTT_ARGS_NUM_MAX] = {
                    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
                };
                for (
                    int i = 0;
                    (i < SNMTT_ARGS_NUM_MAX) && (pldSizeIter > 0);
                    ++i
                ) {
                    /* Valid parser arg... */
                    if (recIdParser->args[i]) {
                        if (
                            recIdParser->args[i]->radix == SNMTT_RADIX_STRING
                        ) {
                            /* String of module... */
                            /* Collecting all the rest payload... */
                            char *moduleStr = malloc(pldSizeIter + 1);
                            Q_ENSURE(moduleStr != (char *)0);
                            memcpy(
                                moduleStr, pldStart + (pldSize - pldSizeIter),
                                pldSizeIter);
                            moduleStr[pldSizeIter] = '\0';
                            fmtArgv[i] = moduleStr; /* To dispMsg. */
                            msgSize += strlen(fmtArgv[i]);
                            pldSizeIter = 0; /* Break loop. */
                        } else if (
                            recIdParser->args[i]->argLen <= pldSizeIter
                        ) {
                            /* Normal parsing... */
                            fmtArgv[i] =
                                SNMTT_itoa(
                                    pldStart + (pldSize - pldSizeIter),
                                    recIdParser->args[i]->argLen,
                                    recIdParser->args[i]->radix);
                            msgSize += strlen(fmtArgv[i]);
                            pldSizeIter -= recIdParser->args[i]->argLen;
                        }
                    }
                }
                char *dispMsg = malloc(msgSize);
                Q_ENSURE(dispMsg != NULL);
                snprintf(dispMsg, msgSize, nFmt, currMsg[0],
                        fmtArgv[0],  fmtArgv[1],  fmtArgv[2],  fmtArgv[3],
                        fmtArgv[4],  fmtArgv[5],  fmtArgv[6],  fmtArgv[7],
                        fmtArgv[8],  fmtArgv[9],  fmtArgv[10], fmtArgv[11],
                        fmtArgv[12], fmtArgv[13], fmtArgv[14], fmtArgv[15]);
                free(nFmt);
                /* Free memory generated from *SNMTT_itoa. */
                for (int i = 0; i < SNMTT_ARGS_NUM_MAX; ++i) {
                    if (fmtArgv[i]) free(fmtArgv[i]);
                }
                /* Send disMsg to Display. */
                GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_MNGR_RECV_MSG_SIG);
                evt->txt = dispMsg;
                QACTIVE_POST(AO_GuiMngr, (QEvt*)evt, (void *)0);
            } else {  /* Invalid RecID. */
                /* Send [Seq.][RecID][pldLen] frame to Display. */
                uint8_t dispMsgLen = 22 + 1;
                char *dispMsg = malloc(dispMsgLen);
                Q_ENSURE(dispMsg != (char *)0);
                snprintf(
                    dispMsg, dispMsgLen, "[%03d][%03d][%03d][????]\n",
                    currMsg[0], currMsg[1], currMsg[2]);
                GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_MNGR_RECV_MSG_SIG);
                evt->txt = dispMsg;
                QACTIVE_POST(AO_GuiMngr, (QEvt*)evt, (void *)0);
            }
            free(((SpMngrEvt *)e)->pld.msgFrm); /*! GC. */
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::SpMngr::SM::active::opening} ......................................*/
static QState SpMngr_opening(SpMngr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SpMngr::SM::active::opening::SP_MNGR_OPEN_COM_SUCCESS} */
        case SP_MNGR_OPEN_COM_SUCCESS_SIG: {
            GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_OPEN_COM_SUCCESS_SIG);
            QACTIVE_POST(AO_GuiMngr, (QEvt *)evt, (void *)0);
            status_ = Q_TRAN(&SpMngr_opened);
            break;
        }
        /*${AOs::SpMngr::SM::active::opening::SP_MNGR_OPEN_COM_FAIL} */
        case SP_MNGR_OPEN_COM_FAIL_SIG: {
            GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_OPEN_COM_FAIL_SIG);
            QACTIVE_POST(AO_GuiMngr, (QEvt *)evt, (void *)0);
            status_ = Q_TRAN(&SpMngr_active);
            break;
        }
        default: {
            status_ = Q_SUPER(&SpMngr_active);
            break;
        }
    }
    return status_;
}

/*${AOs::SpMngr::SM::active::opened} .......................................*/
static QState SpMngr_opened(SpMngr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SpMngr::SM::active::opened::SP_MNGR_CLOSE_COM_SUCCESS} */
        case SP_MNGR_CLOSE_COM_SUCCESS_SIG: {
            GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_MNGR_CLOSE_COM_SUCCESS_SIG);
            QACTIVE_POST(AO_GuiMngr, (QEvt *)evt, (void *)0);
            status_ = Q_TRAN(&SpMngr_active);
            break;
        }
        /*${AOs::SpMngr::SM::active::opened::SP_MNGR_PORT_ERR_SHUT_DOWN} */
        case SP_MNGR_PORT_ERR_SHUT_DOWN_SIG: {
            GuiMngrEvt *evt = Q_NEW(GuiMngrEvt, GUI_MNGR_PORT_ERR_SHUT_DOWN_SIG);
            QACTIVE_POST(AO_GuiMngr, (QEvt *)evt, (void *)0);
            status_ = Q_TRAN(&SpMngr_active);
            break;
        }
        /*${AOs::SpMngr::SM::active::opened::SP_MNGR_CLOSE_SERIAL_PORT} */
        case SP_MNGR_CLOSE_SERIAL_PORT_SIG: {
            /* Close port. */
            BSP_Post2LspThread(
                SP_TRD_CLOSE_PORT_SIG,
                (char *)0, 0, 0, 0, 0, 0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SpMngr::SM::active::opened::SP_MNGR_RECV_PACKET} */
        case SP_MNGR_RECV_PACKET_SIG: {
            /**
             * Parse the received byte package based on current protocal
             * and generate the frame to Display...
             */
            for (int i = 0; i < ((SpMngrEvt *)e)->pldSize.packSize; ++i) {
                HLDCParser_trigger(((SpMngrEvt *)e)->pld.packBuf[i]);
            }
            free(((SpMngrEvt *)e)->pld.packBuf);  /*! GC. */
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&SpMngr_active);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::SpMngr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
